# Generated by Django 6.0.5 on 2026-10-05 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: 10-A', max_length=20, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comunicado', 'Comunicado'), ('tarea', 'Tarea'), ('evento', 'Evento')], default='comunicado', max_length=20, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publicado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('grupos', models.ManyToManyField(blank=True, help_text='Déjelo vacío para que lo vea todo el colegio.', to='Main.grupo', verbose_name='grupos destinatarios')),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-publicado'],
            },
        ),
        migrations.CreateModel(
            name='ClaseHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')], verbose_name='día')),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora de fin')),
                ('salon', models.CharField(blank=True, max_length=30, verbose_name='salón')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.asignatura', verbose_name='asignatura')),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to=settings.AUTH_USER_MODEL, verbose_name='profesor')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='Main.grupo', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'clase del horario',
                'verbose_name_plural': 'clases del horario',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250, verbose_name='texto')),
                ('visible_desde', models.DateField(default=django.utils.timezone.localdate, verbose_name='visible desde')),
                ('visible_hasta', models.DateField(blank=True, help_text='Opcional. Vacío = sin fecha de fin.', null=True, verbose_name='visible hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('grupos', models.ManyToManyField(blank=True, help_text='Déjelo vacío para que lo vea todo el colegio.', to='Main.grupo', verbose_name='grupos destinatarios')),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'avisos',
                'ordering': ['-visible_desde', '-id'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Solo para estudiantes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='Main.grupo', verbose_name='grupo'),
        ),
    ]
