# Generated by Django 6.0.5 on 2026-10-06 05:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_asignatura_grupo_comunicado_clasehorario_aviso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='nombre')),
                ('url', models.URLField(max_length=600, validators=[django.core.validators.URLValidator(schemes=['https'])], verbose_name='enlace')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'espacio',
                'verbose_name_plural': 'espacios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Franja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(help_text='1 es la primera franja del día.', unique=True, verbose_name='orden')),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora de fin')),
                ('es_descanso', models.BooleanField(default=False, verbose_name='es un descanso')),
            ],
            options={
                'verbose_name': 'franja de la jornada',
                'verbose_name_plural': 'franjas de la jornada',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'grupo', 'verbose_name_plural': 'grupos'},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='es_materia',
            field=models.BooleanField(default=True, help_text='Desmárquelo para entradas como «Trabajo autónomo» o «Dir. de grupo»: salen en la tabla del horario, pero no llevan profesor ni aparecen en «Horario de hoy».', verbose_name='es una materia'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='icono',
            field=models.CharField(choices=[('tecnologia', 'Tecnología (monitor)'), ('educacion_fisica', 'Educación física (persona)'), ('artistica', 'Artística (paleta)'), ('etica', 'Ética (balanza)'), ('religion', 'Religión (cruz)'), ('lengua', 'Lengua castellana (libro)'), ('sociales', 'Sociales (globo)'), ('matematicas', 'Matemáticas (calculadora)'), ('biologia', 'Biología (microscopio)'), ('quimica', 'Química (matraz)'), ('fisica', 'Física (átomo)'), ('filosofia', 'Filosofía (interrogación)'), ('ingles', 'Inglés (globo de diálogo)'), ('general', 'General (portátil)')], default='general', max_length=20, verbose_name='ícono'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nombre_corto',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se muestra bajo el ícono de Teams. Si está vacío se usa el nombre completo.', max_length=30, verbose_name='nombre corto'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_dirigidos', to=settings.AUTH_USER_MODEL, verbose_name='director de grupo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posición en la cuadrícula de la página de horarios (1 va primero).', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='clasehorario',
            name='hora_fin',
            field=models.TimeField(editable=False, verbose_name='hora de fin'),
        ),
        migrations.AlterField(
            model_name='clasehorario',
            name='hora_inicio',
            field=models.TimeField(editable=False, verbose_name='hora de inicio'),
        ),
        migrations.AlterField(
            model_name='clasehorario',
            name='profesor',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para materias. Se deja vacío en «Trabajo autónomo» y «Dir. de grupo».', limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to=settings.AUTH_USER_MODEL, verbose_name='profesor'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: 11°  o  4°A', max_length=20, unique=True, verbose_name='nombre'),
        ),
        migrations.CreateModel(
            name='EnlaceMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600, validators=[django.core.validators.URLValidator(schemes=['https'])], verbose_name='enlace de Teams')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de los íconos en la ventana.', verbose_name='orden')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.asignatura', verbose_name='asignatura')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='Main.grupo', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'enlace de Teams de una materia',
                'verbose_name_plural': 'enlaces de Teams de las materias',
                'ordering': ['orden', 'asignatura__nombre'],
            },
        ),
        migrations.AddField(
            model_name='clasehorario',
            name='franja',
            field=models.ForeignKey(limit_choices_to={'es_descanso': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='Main.franja', verbose_name='franja'),
        ),
        migrations.AddConstraint(
            model_name='clasehorario',
            constraint=models.UniqueConstraint(fields=('grupo', 'dia', 'franja'), name='unica_clase_por_grupo_y_franja', violation_error_message='Ese grupo ya tiene una clase en esa franja.'),
        ),
        migrations.AddConstraint(
            model_name='clasehorario',
            constraint=models.UniqueConstraint(fields=('profesor', 'dia', 'franja'), name='unica_clase_por_profesor_y_franja', violation_error_message='Ese profesor ya tiene una clase en esa franja.'),
        ),
        migrations.AddConstraint(
            model_name='enlacemateria',
            constraint=models.UniqueConstraint(fields=('grupo', 'asignatura'), name='unico_enlace_por_grupo_y_asignatura', violation_error_message='Ese grupo ya tiene un enlace para esa asignatura.'),
        ),
    ]
