# Generated by Django 6.0.5 on 2026-10-06 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_espacio_franja_alter_grupo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('grados', models.CharField(blank=True, help_text='Ej.: "Grado 1° - 3°"', max_length=40, verbose_name='grados')),
                ('descripcion', models.CharField(blank=True, max_length=160, verbose_name='descripción')),
                ('es_transversal', models.BooleanField(default=False, help_text='Se muestra en el centro de la biblioteca. Solo debería haber uno.', verbose_name='es el ciclo central (transversal)')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'ciclo',
                'verbose_name_plural': 'ciclos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AreaBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('detalle', models.CharField(blank=True, help_text='Ej.: "Castellano · Inglés"', max_length=60, verbose_name='detalle')),
                ('icono', models.CharField(choices=[('tecnologia', 'Tecnología (monitor)'), ('educacion_fisica', 'Educación física (persona)'), ('artistica', 'Artística (paleta)'), ('etica', 'Ética (balanza)'), ('religion', 'Religión (cruz)'), ('lengua', 'Lengua castellana (libro)'), ('sociales', 'Sociales (globo)'), ('matematicas', 'Matemáticas (calculadora)'), ('biologia', 'Biología (microscopio)'), ('quimica', 'Química (matraz)'), ('fisica', 'Física (átomo)'), ('filosofia', 'Filosofía (interrogación)'), ('ingles', 'Inglés (globo de diálogo)'), ('general', 'General (portátil)')], default='general', max_length=20, verbose_name='ícono')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Main.ciclo', verbose_name='ciclo')),
            ],
            options={
                'verbose_name': 'área de la biblioteca',
                'verbose_name_plural': 'áreas de la biblioteca',
                'ordering': ['ciclo__orden', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('ciclo', 'nombre'), name='area_unica_por_ciclo', violation_error_message='Ese ciclo ya tiene un área con ese nombre.')],
            },
        ),
    ]
