# Generated by Django 6.0.5 on 2026-10-07 00:13

import Main.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_ciclo_areabiblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='Main.ciclo', verbose_name='ciclo de la biblioteca'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('guia', 'Guía'), ('taller', 'Taller'), ('lectura', 'Lectura'), ('presentacion', 'Presentación'), ('evaluacion', 'Evaluación'), ('video', 'Video'), ('otro', 'Otro')], default='guia', max_length=15, verbose_name='tipo')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')], default=1, verbose_name='periodo')),
                ('todo_ciclo', models.BooleanField(default=False, help_text='Visible para todos los grupos del ciclo.', verbose_name='todo el ciclo')),
                ('archivo', models.FileField(blank=True, upload_to=Main.models.ruta_material, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'jpg', 'jpeg', 'png', 'zip', 'mp4'])], verbose_name='archivo')),
                ('nombre_archivo', models.CharField(blank=True, editable=False, max_length=200)),
                ('tamano', models.PositiveIntegerField(default=0, editable=False)),
                ('enlace', models.URLField(blank=True, help_text='Drive, YouTube, Teams… debe empezar con https://', verbose_name='enlace')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='Main.areabiblioteca', verbose_name='área')),
                ('grupos', models.ManyToManyField(blank=True, related_name='materiales', to='Main.grupo', verbose_name='grupos')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to=settings.AUTH_USER_MODEL, verbose_name='publicado por')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'ordering': ['-creado'],
            },
        ),
    ]
